from typing import Protocol
from app.domain import DocumentRecord, JobRecord, JobStage, JobStatus

class Repository(Protocol):
    def initialize(self) -> None: ...
    def create_document(self, filename: str, collection: str, mime_type: str, file_size: int, source_path: str, content_hash: str) -> DocumentRecord: ...
    def get_document(self, document_id: str) -> DocumentRecord: ...
    def list_documents(self, collection: str | None = None) -> list[DocumentRecord]: ...
    def update_document_source_path(self, document_id: str, source_path: str) -> DocumentRecord: ...
    def mark_document_indexing(self, document_id: str) -> None: ...
    def mark_document_indexed(self, document_id: str, chunk_count: int) -> None: ...
    def mark_document_failed(self, document_id: str, error: str) -> None: ...
    def set_document_text_path(self, document_id: str, text_path: str) -> None: ...
    def create_job(self, document_id: str, collection: str) -> JobRecord: ...
    def set_job_rq_id(self, job_id: str, rq_job_id: str) -> None: ...
    def get_job(self, job_id: str) -> JobRecord: ...
    def get_job_by_rq_id(self, rq_job_id: str) -> JobRecord: ...
    def update_job(self, job_id: str, status: JobStatus, stage: JobStage, progress: int, error: str | None = None) -> None: ...
    def replace_chunks(self, document_id: str, collection: str, chunks: list[dict]) -> None: ...
    def store_parent_chunk(self, id: str, document_id: str, collection: str, text: str, chunk_index: int) -> None: ...
    def get_parent_chunk(self, parent_id: str) -> str | None: ...
    def list_all_child_texts(self) -> list[str]: ...
    def list_all_chunks_for_bm25(self) -> list[dict]: ...
